sc stop SN-Server
sc stop SN-ngrok
sc stop SN-Tasks
sc stop SN-Integrator
sc stop SN-Inventory
TIMEOUT /t 3
sc start SN-ngrok
sc start SN-Server
sc start SN-Tasks
sc start SN-Integrator
sc start SN-Inventory